be_landmarks = {
    'Computer Schule Bern': set(['Eigerplatz', 'Hasler']),
    'Bahnhof Weissenbühl': set(['Beaumont']),
    'City West': set(['Kocherpark', 'City West']),
    'Vancouver Lookout': set(['Waterfront']),
    'Canada Place': set(['Burrard', 'Waterfront']),
    'Cathedral of Our Lady of the Holy Rosary': set(['Vancouver City Centre', 'Granville']),
    'Library Square': set(['Vancouver City Centre', 'Stadium-Chinatown']),
    'B.C. Place Stadium': set(['Stadium-Chinatown']),
    'Lions Gate Bridge': set(['Burrard']),
    'Gastown Steam Clock': set(['Waterfront']),
    'Waterfront Station': set(['Waterfront']),
    'Granville Street': set(['Granville', 'Vancouver City Centre']),
    'Pacific Central Station': set(['Main Street-Science World']),
    'Prospect Point Lighthouse': set(['Burrard']),
    'Queen Elizabeth Theatre': set(['Stadium-Chinatown']),
    'Stanley Park': set(['Burrard']),
    'Granville Island Public Market': set(['Yaletown-Roundhouse']),
    'Kitsilano Beach': set(['Olympic Village']),
    'Dr. Sun Yat-Sen Classical Chinese Garden': set(['Stadium-Chinatown']),
    'Museum of Vancouver': set(['Yaletown-Roundhouse']),
    'Science World': set(['Main Street-Science World']),
    'Robson Square': set(['Vancouver City Centre']),
    'Samson V Maritime Museum': set(['Columbia']),
    'Burnaby Lake': set(['Sperling / Burnaby Lake', 'Lake City Way', 'Production Way / University']),
    'Nikkei National Museum & Cultural Centre': set(['Edmonds']),
    'Central Park': set(['Patterson', 'Metrotown'])
}
