# -*- coding: utf-8 -*-
be_metro = {
    'Weissenbühl': set(['Beaumont']),
    'Beaumont': set(['Eigerplatz', 'Weissenbühl']),
    'Eigerplatz': set(['Monbijou', 'Weissensteinstrasse', 'Hasler', 'Beaumont']),
    'Hasler': set(['Kocherpark', 'Eigerplatz']),
    'Kocherpark': set(['Hirschengraben', 'Kaufmannischer Verband', 'Hasler']),
    'Hirschengraben': set(['Bern Bahnhof', 'Monbijou', 'Kocherpark']),
    'Bern Bahnhof': set(['Hirschengraben', 'Monbijou', 'Bärenplatz']),
    'Köniz Schliern': set(['Eichmatt']),
    'Eichmatt': set(['Sandwürfi Friedhof', 'Köniz Schliern']),
    'Sandwürfi Friedhof': set(['Köniz Schloss', 'Eichmatt']),
    'Köniz Schloss': set(['Köniz Zentrum', 'Sandwürfi Friedhof']),
    'Köniz Zentrum': set(['Brühlplatz', 'Köniz Schloss']),
    'Brühlplatz': set(['Liebefeld Park', 'Köniz Zentrum']),
    'Liebefeld Park': set(['Hessstrasse', 'Brühlplatz']),
    'Hessstrasse': set(['Dübystrasse', 'Liebefeld Park']),
    'Dübystrasse': set(['Weissensteinstrasse', 'Hessstrasse']),
    'Weissensteinstrasse': set(['Eigerplatz', 'Dübystrasse']),
    'Wabern': set(['Eichholz']),
    'Eichholz': set(['Gurtenbahn', 'Wabern']),
    'Gurtenbahn': set(['Sandrain', 'Eichholz']),
    'Sandrain': set(['Schönegg', 'Gurtenbahn']),
    'Schönegg': set(['Wander', 'Sandrain']),
    'Wander': set(['Sulgenau', 'Schönegg']),
    'Sulgenau': set(['Monbijou', 'Wander']),
    'Monbijou': set(['Hirschengraben', 'Sulgenau', 'Eigerplatz', 'Bern Bahnhof']),
    'Fischermätteli': set(['Munzinger']),
    'Munzinger': set(['Pestalozzi', 'Fischermätteli']),
    'Pestalozzi': set(['Cäcilienstrasse', 'Munzinger']),
    'Cäcilienstrasse': set(['Brunnhof', 'Pestalozzi']),
    'Brunnhof': set(['Kaufmannischer Verband', 'Cäcilienstrasse']),
    'Kaufmannischer Verband': set(['Kocherpark', 'Brunnhof']),
    'Bärenplatz': set(['Bern Bahnhof', 'Zytglogge']),
    'Zytglogge': set(['Bärenplatz', 'Kursaal']),
    'Kursaal': set(['Zytglogge', 'Viktoriaplatz']),
    'Viktoriaplatz': set(['Kursaal', 'Salem', 'Spitalacker']),
    'Spitalacker': set(['Viktoriaplatz', 'Breitenrain']),
    'Breitenrain': set(['Spitalacker', 'Parkstrasse']),
    'Parkstrasse': set(['Breitenrain', 'Guisanplatz Expo']),
    'Guisanplatz Expo': set(['Parkstrasse', 'Wankdorf Center']),
    'Wankdorf Center': set(['Wankdorfplatz', 'Guisanplatz Expo']),
    'Wankdorfplatz': set(['Wankdorf Center', 'Wankdorf Bahnhof']),
    'Wankdorf Bahnhof': set(['Wankdorfplatz']),
    'Salem': set(['Viktoriaplatz', 'Schönburg']),
    'Schönburg': set(['Salem', 'Rosengarten']),
    'Rosengarten': set(['Schönburg', 'Galgenfeld']),
    'Galgenfeld': set(['Rosengarten', 'Schosshaldenfriedhof']),
    'Schosshaldenfriedhof': set(['Galgenfeld', 'Waldeck']),
    'Waldeck': set(['Schosshaldenfriedhof', 'Ostermundigen Bahnhof']),
    'Ostermundigen Bahnhof': set(['Waldeck', 'Zollgasse']),
    'Zollgasse': set(['Ostermundigen Bahnhof'])
}
"""
    WegmühlegässliSportplatzwegOberfeldOstermundigen Rüti

"""
