var canvArrow,titleMe,imageMe,scrollMe,topMe,bottomMe,chapterLinks,num_chapter,cp,resizeId,lines_x,lines_y,language="de",lang_str={Object_de:"Objekt",back_to_main_menu_de:"oder zur\u00c3\u00bcck zum Hauptmenu",Object_en:"Object",back_to_main_menu_en:"or back to main menu"};function msieversion(){var a=window.navigator.userAgent,d=a.indexOf("MSIE ");return 0<d?parseInt(a.substring(d+5,a.indexOf(".",d))):0}
function loadXMLDoc(a,d,b){xmlhttp=new XMLHttpRequest;xmlhttp.onreadystatechange=d;xmlhttp.open("GET",a,!0);xmlhttp.send()}function change_language(a){"wechseln zu deutsch"==a.innerHTML?(language="de",a.innerHTML="change to english"):(language="en",a.innerHTML="wechseln zu deutsch");page_load.load_ext(!1,build_chapter.text[num_chapter[1]].count)}function go_top(){topMe.scrollIntoView({block:"end",behavior:"smooth"})}
function open_ext(a,d){"undefined"==d?window.open("http://"+a,"_blank"):(build_chapter.text[num_chapter[1]].count++,cycle_in_view_code())}
function cycle_in_view_code(){build_chapter.text[num_chapter[1]].count>build_chapter.text[num_chapter[1]].url_epi.length-1&&(build_chapter.text[num_chapter[1]].count=0);0>build_chapter.text[num_chapter[1]].count&&(build_chapter.text[num_chapter[1]].count=build_chapter.text[num_chapter[1]].url_epi.length-1);imageMe.innerHTML="<div></div>"+display_code(window[build_chapter.text[num_chapter[1]].objs[build_chapter.text[num_chapter[1]].count]]);bottomMe.innerHTML=lang_str["Object_"+language]+" &quot;"+
build_chapter.text[num_chapter[1]].objs[build_chapter.text[num_chapter[1]].count]+"&quot; ("+parseInt(build_chapter.text[num_chapter[1]].count+1)+"/"+build_chapter.text[num_chapter[1]].url_epi.length+"): "+build_chapter.text[num_chapter[1]].url_epi[build_chapter.text[num_chapter[1]].count]+build_chapter.text[num_chapter[1]].ih}
var page_load={load_ext:function(a,d){loadXMLDoc("botsi_first/text/"+language+".txt",function(){4==xmlhttp.readyState&&(200==xmlhttp.status?(build_chapter.text=JSON.parse(xmlhttp.responseText),num_chapter=Object.keys(build_chapter.text),loadXMLDoc("botsi_first/text/about_me_"+language+".html",function(){4==xmlhttp.readyState&&(200==xmlhttp.status?(build_chapter.text[num_chapter[4]].ih=xmlhttp.responseText,build_chapter.text[num_chapter[1]].count=0,build_chapter.text[num_chapter[1]].objs=["draw_net",
"build_chapter","page_load"],1==a?page_load.second():page_load.update(d)):alert("get about_me shit happens"))})):alert("get de shit happens"))})},first:function(){canvArrow=document.getElementById("arrow_Canvas");titleMe=document.getElementById("titleme");imageMe=document.getElementById("imageme");scrollMe=document.getElementById("scrollme");topMe=document.getElementById("topme");bottomMe=document.getElementById("bottomme");chapterLinks=document.getElementsByClassName("scrollme_content");"en"==(0==
msieversion()?window.navigator.language.slice(0,2):window.navigator.browserLanguage.slice(0,2))&&(language="en",titleMe.getElementsByTagName("span")[0].innerHTML="wechseln zu deutsch");page_load.load_ext(!0)},second:function(){canvArrow.addEventListener("click",add_query_switch,!1);bottomMe.addEventListener("click",add_query_switch,!1);canvArrow.addEventListener("mouseover",function(){build_chapter.switchme_allow=!1},!1);titleMe.addEventListener("click",go_top,!1);for(var a in build_chapter.text){var d=
document.createElement("span");d.className="scrollme_content";d.innerHTML=a;d.addEventListener("click",function(){build_chapter.show(this)},!1);scrollMe.appendChild(d)}resizeCanvas();go_top()},update:function(a){build_chapter.text[num_chapter[1]].count=a;a=scrollMe.getElementsByTagName("span");var d=0,b;for(b in build_chapter.text)a[d].innerHTML==build_chapter.old_c&&(build_chapter.old_c=b),a[d].innerHTML=b,d++;"intro"!=build_chapter.old_c&&(imageMe.className=build_chapter.old_c,bottomme.innerHTML=
build_chapter.text[build_chapter.old_c].ih,imageMe.classList[0]==num_chapter[1]&&cycle_in_view_code())}};function add_query_switch(){0!=build_chapter.draw_allow&&(build_chapter.text[imageMe.className]&&"undefined"!==typeof build_chapter.text[imageMe.className].url?build_chapter.query_switch(imageMe.className):go_top())}
var build_chapter={old_c:"intro",set_mb:function(){document.getElementById("cv_table").style.padding=parseInt(draw_net.indent_y)+"px 0"},draw_allow:!0,show:function(a){setTimeout(function(){build_chapter.draw_allow=!0},800);this.draw_allow=!1;draw_net.spherize=cp;""!=this.old_c&&imageMe.classList.remove(this.old_c);a=a.innerHTML;imageMe.classList.add(a);imageMe.innerHTML=a!=num_chapter[1]?"":"<div></div>"+display_code(window[this.text[num_chapter[1]].objs[this.text[num_chapter[1]].count]]);bottomMe.innerHTML=
a!=num_chapter[1]?this.text[a].ih:lang_str["Object_"+language]+" &quot;"+this.text[num_chapter[1]].objs[this.text[num_chapter[1]].count]+"&quot; ("+parseInt(this.text[num_chapter[1]].count+1)+"/"+this.text[num_chapter[1]].url_epi.length+"): "+this.text[num_chapter[1]].url_epi[this.text[num_chapter[1]].count]+this.text[num_chapter[1]].ih;a==num_chapter[4]?(bottomMe.style.cssText="bottom:auto;height:100%;background:none;box-shadow:none;",this.set_mb(),bottomMe.getElementsByTagName("a")[bottomMe.getElementsByTagName("a").length-
1].scrollIntoView({block:"start",behavior:"smooth"})):(bottomMe.style.cssText="bottom:0;height:auto;background:rgba(255, 255, 255, 0.5);box-shadow:0px 75px 36px 111px rgba(255, 255, 255, 0.5);margin-bottom:"+parseInt(draw_net.indent_y)+"px",bottomMe.scrollIntoView({block:"start",behavior:"smooth"}));this.old_c=a},switchme_op:1,switchme_allow:!1,query_switch:function(a,d){if(!(200>draw_net.wh_store[1]||draw_net.wh_store[1]>canvArrow.height-200))if(0!=a){document.getElementById("switchme")&&scrollMe.removeChild(document.getElementById("switchme"));
var b=0;1<this.text[a].url.length&&(b+=parseInt(draw_net.wh_store[0]/(.33*canvArrow.width)),draw_net.wh_store[1]>=canvArrow.height/2&&(b+=3));var f=document.createElement("div");f.id="switchme";var b="<span onclick=\"build_chapter.query_switch(0);open_ext('"+this.text[a].url[b]+this.text[a].url_epi[b]+"','"+typeof this.text[a].count+"')\">"+this.text[a].prelink+this.text[a].url[b]+"</span>",c;c=250>draw_net.spherize?'<hr/><span onclick="build_chapter.query_switch(0);go_top();">'+lang_str["back_to_main_menu_"+
language]+"</span>":"";f.innerHTML=b+c;scrollMe.appendChild(f);this.switchme_allow=!0;f.style.left=draw_net.wh_store[0]-100+"px";f.style.top=250>draw_net.spherize?draw_net.wh_store[1]-50+"px":draw_net.wh_store[1]-25+"px"}else scrollMe.removeChild(document.getElementById("switchme"))}},draw_net={draw_all:function(a,d){if(!(a<this.indent_x||a>canvArrow.width-this.indent_x||d<this.indent_y||d>canvArrow.height-this.indent_y)){this.wh_store=[a,d];document.getElementById("switchme")&&0==build_chapter.switchme_allow&&
(build_chapter.switchme_op-=.01,0>=build_chapter.switchme_op?(scrollMe.removeChild(document.getElementById("switchme")),build_chapter.switchme_op=1,build_chapter.switchme_allow=!1):document.getElementById("switchme").style.opacity=build_chapter.switchme_op);var b=canvArrow.getContext("2d");b.clearRect(0,0,canvArrow.width,canvArrow.height);this.draw_center_x(a,d,b)}},draw_center_x:function(a,d,b){b.globalCompositeOperation="source-over";b.beginPath();b.fillStyle="#fff";var f=parseInt((a-1-this.indent_x)/
50),c=lines_x[f],e=this.giveMeC(c,a,canvArrow.width);b.moveTo(c,0);b.lineTo(c,d-this.dw_param[2]);b.bezierCurveTo(c,d-this.dw_param[1],c+e,d-this.dw_param[0],c+e,d);b.bezierCurveTo(c+e,d+this.dw_param[0],c,d+this.dw_param[1],c,d+this.dw_param[2]);b.lineTo(c,canvArrow.height);b.lineTo(c+50,canvArrow.height);c=lines_x[f+1];e=this.giveMeC(c,a,canvArrow.width);b.lineTo(c,d+this.dw_param[2]);b.bezierCurveTo(c,d+this.dw_param[1],c+e,d+this.dw_param[0],c+e,d);b.bezierCurveTo(c+e,d-this.dw_param[0],c,d-this.dw_param[1],
c,d-this.dw_param[2]);b.lineTo(c,0);b.lineTo(c-50,0);b.fill();b.closePath();this.draw_center_y(a,d,b)},draw_center_y:function(a,d,b){b.globalCompositeOperation="destination-in";b.beginPath();b.fillStyle="#fff";var f=parseInt((d-1-this.indent_y)/50),c=lines_y[f],e=this.giveMeC(c,d,canvArrow.height);b.moveTo(0,c);b.lineTo(a-this.dw_param[2],c);b.bezierCurveTo(a-this.dw_param[1],c,a-this.dw_param[0],c+e,a,c+e);b.bezierCurveTo(a+this.dw_param[0],c+e,a+this.dw_param[1],c,a+this.dw_param[2],c);b.lineTo(canvArrow.width,
c);b.lineTo(canvArrow.width,c+50);c=lines_y[f+1];e=this.giveMeC(c,d,canvArrow.height);b.lineTo(a+this.dw_param[2],c);b.bezierCurveTo(a+this.dw_param[1],c,a+this.dw_param[0],c+e,a,c+e);b.bezierCurveTo(a-this.dw_param[0],c+e,a-this.dw_param[1],c,a-this.dw_param[2],c);b.lineTo(0,c);b.lineTo(0,c-50);b.fill();b.closePath();b.globalCompositeOperation="xor";b.beginPath();b.fillStyle="#fff";b.fillRect(0,0,canvArrow.width,canvArrow.height);b.closePath();b.globalCompositeOperation="source-over";3>this.spherize&&
(b.beginPath(),b.lineWidth=50,b.strokeStyle="#fff",b.arc(a,d,parseInt(.5*cp/this.spherize+25),0,2*Math.PI),b.stroke(),b.closePath());this.draw_lines_x(a,d,b)},draw_lines_x:function(a,d,b){b.beginPath();b.lineWidth=1;b.strokeStyle="#999";for(var f=0;f<lines_x.length;f++){var c=lines_x[f],e=0;c<a+.5*cp&&c>a-.5*cp&&(e=this.giveMeC(c,a,canvArrow.width));b.moveTo(c,0);b.lineTo(c,d-this.dw_param[2]);b.bezierCurveTo(c,d-this.dw_param[1],c+e,d-this.dw_param[0],c+e,d);b.bezierCurveTo(c+e,d+this.dw_param[0],
c,d+this.dw_param[1],c,d+this.dw_param[2]);b.lineTo(c,canvArrow.height)}b.stroke();b.closePath();this.draw_lines_y(a,d,b)},draw_lines_y:function(a,d,b){b.beginPath();for(var f=0;f<lines_y.length;f++){var c=lines_y[f],e=0;c<d+.5*cp&&c>d-.5*cp&&(e=this.giveMeC(c,d,canvArrow.height));b.moveTo(0,c);b.lineTo(a-this.dw_param[2],c);b.bezierCurveTo(a-this.dw_param[1],c,a-this.dw_param[0],c+e,a,c+e);b.bezierCurveTo(a+this.dw_param[0],c+e,a+this.dw_param[1],c,a+this.dw_param[2],c);b.lineTo(canvArrow.width,
c)}b.stroke();b.closePath()},wh_store:[0,0],dw_param:[200,300,500],spherize:3,giveMeC:function(a,d,b){b=cp;d>a&&(b=-cp);return(d-a+.5*b)/this.spherize},eye_scroll:function(a){bottomMe.style.cursor=canvArrow.style.cursor=20<a?"default":"pointer";2.5>a&&(a=2.5);300<a&&(a=300);this.spherize=a;this.draw_all(this.wh_store[0],this.wh_store[1])}};
function display_code(a){var d="",b;for(b in a)a.hasOwnProperty(b)&&(d=d+b.toString()+" : ",d=d+a[b].toString().replace("<hr/>","").replace(/{/g,"<br/>{<br/>").replace(/}/g,"}<br/>").replace(/;/g,";<br/>")+"<br/>");return d}document.addEventListener("DOMContentLoaded",page_load.first,!1);
"ontouchstart"in window?window.addEventListener("touchmove",function(a){draw_net.draw_all(a.changedTouches[0].clientX,a.changedTouches[0].clientY)},!1):(window.addEventListener("mousemove",function(a){draw_net.draw_all(a.clientX,a.clientY)},!1),window.addEventListener("keydown",arrow,!1));window.addEventListener("scroll",function(a){draw_net.eye_scroll(300-window.pageYOffset)},!1);window.addEventListener("resize",pre_resizeCanvas,!1);
function pre_resizeCanvas(){clearTimeout(resizeId);resizeId=setTimeout(function(){resizeCanvas()},200)}
function resizeCanvas(){lines_x=[];lines_y=[];canvArrow.width=window.innerWidth;canvArrow.height=window.innerHeight;draw_net.indent_x=parseInt(canvArrow.width%50/2);draw_net.indent_y=parseInt(canvArrow.height%50/2);for(var a=draw_net.indent_x;a<canvArrow.width;a+=50)lines_x.push(a);for(a=draw_net.indent_y;a<canvArrow.height;a+=50)lines_y.push(a);cp=(canvArrow.width+canvArrow.height)/2;draw_net.dw_param=[.18*cp,.18*cp,.4*cp];draw_net.spherize=cp;scrollMe.style.height=imageMe.style.height=window.innerHeight+
300+"px";titleMe.style.margin="0 "+parseInt(50+draw_net.indent_x)+"px";titleMe.style.top=parseInt(100+draw_net.indent_y)+"px";titleMe.style.width=parseInt(canvArrow.width-100-2*draw_net.indent_x)+"px";bottomMe.style.marginBottom=parseInt(draw_net.indent_y)+"px";null!=document.getElementById("cv_table")&&build_chapter.set_mb();for(a=0;a<chapterLinks.length;a++)chapterLinks[a].style.top=titleMe.style.top,0<a&&(chapterLinks[a-1].getBoundingClientRect().top<chapterLinks[a].getBoundingClientRect().top?
chapterLinks[a].style.marginLeft=parseInt(50+draw_net.indent_x)+"px":chapterLinks[a].style.marginLeft="50px");chapterLinks[0].style.marginLeft=parseInt(50+draw_net.indent_x)+"px";draw_net.draw_all(.5*canvArrow.width,.5*canvArrow.height)}function arrow(a){imageMe.classList[0]==num_chapter[1]&&(a||(a=window.event),37==a.keyCode&&(build_chapter.text[num_chapter[1]].count--,cycle_in_view_code()),39==a.keyCode&&(build_chapter.text[num_chapter[1]].count++,cycle_in_view_code()))};